services:
    streamlit-app:
        build: .
        container_name: gsheets_dashboard
        restart: always
        ports:
            - '8501:8501'
        volumes:
            - ./data:/app/data
